class DataTypes:
    string = "TEXT"
    medium_string = "MEDIUMTEXT"
    long_string = "LONGTEXT"
    binary = "BINARY"
    list = "SET"
    bool = "BOOL"
    small_int = "SMALLINT"
    medium_int = "MEDIUMINT"
    int = "INT"
    big_int = "BIGINT"
    float = "FLOAT"
    double = "DOUBLE"
    datetime = "DATETIME"
    primary_key = "PRIMARY KEY"
